### ISSUE TITLE
Give the caller the ability to adjust where the horizontal stepper renders. 

### ISSUE THREAD

**Issue by downright-development** [ayonshafiul/react-native-reanimated-progress-steps#1]
I tried to center this when not extended and found no way to center. Really the container style props should just be exposed to let the user to style these themselves

**Comment by ayonshafiul** [comment]
```js
<SafeAreaView style={{ flex: 1 }}>
      <ProgressStepperProvider>
        <View
          style={{
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          <ProgressStepper />
        </View>
      </ProgressStepperProvider>
    </SafeAreaView>
```
 You can create your own wrapper view to position it anywhere you want. You can also set the width and height of the wrapper view to position it top of the screen as well. 

![image](https://github.com/user-attachments/assets/d80d6e70-0f2a-4fe6-81f3-cd25b81a6f58)

**Comment by downright-development** [comment]
Thanks! That resolved my issue - I would love to see some more comprehensive documents as this product grows <3
